### PR TITLE
colored units in a file

### PR DESCRIPTION
**Pull request by TheRealDarkCoder**
Issue was reported to put Hashtags before color values. A file had missing hashtags,

### CODE REVIEW

**Comment by TheZZGamer** [comment]
ya just one file :P

**Comment by andymeneely** [comment]
You'll also need to add the actual logic of adding the `#` to here: https://github.com/andymeneely/game_icons/blob/master/lib/game_icons/icon.rb#L19-L20

Then update the tests to make sure they have all the combos.

Thanks!!

**Comment by TheRealDarkCoder** [comment]
you mean replace bg and fg with their values?

**Comment by andymeneely** [comment]
Yeah - prepend a `#` to `fg` and `bg` if they don't already have one.

**Pull request merged**
